In [1]:
 # Hello Panda


import numpy as np
import pandas as pd

# 1. Create a NumPy Array (The raw math layer)
my_list = [[10, 20], [30, 40]]
data_array = np.array(my_list)
print (type(data_array))
# 2. Wrap it in Pandas (The friendly label layer)
# We use the numpy array 'data_array' to build the dataframe
df = pd.DataFrame(data_array, columns=['Price', 'Quantity'])

print("--- The Pandas DataFrame ---")
print(df)

print("\n--- The Underlying NumPy Array ---")
# You can pull the raw NumPy array back out using .values
print(df.values)


<class 'numpy.ndarray'>
--- The Pandas DataFrame ---
   Price  Quantity
0     10        20
1     30        40

--- The Underlying NumPy Array ---
[[10 20]
 [30 40]]


### Two diamentional Array

In [2]:
array = np.array(range(5))

In [3]:
array

array([0, 1, 2, 3, 4])

In [4]:
two_dia_array = np.array([range(5),range(5)])
two_dia_array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [5]:
two_dia_array +2 

array([[2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6]])

In [6]:
two_dia_array.shape

(2, 5)

In [7]:
two_dia_array.size

10

# Assignment 1: Array Basics

Hi there,

Can you import Numpy and convert the following list comprehension (I just learned about comprehensions in an awesome course by Maven) into an array?

Once you've done that report the following about the array:
* The number of dimensions 
* The shape
* The number of elements in the array
* The type of data contained inside

In [25]:
my_list = [x * 10 for x in range(1, 11)]

In [34]:
myArray =np.array( my_list ).reshape(5,2)
myArray

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [27]:
print (myArray.ndim )
print (myArray.shape )
print (myArray.size )
print (myArray.dtype )


1
(10,)
10
int64


In [8]:
a2= np.ones(2,)
a2
# OR
a2= np.ones(2,dtype='int')
a2

array([1, 1])

In [9]:
a3= np.zeros((2,5),dtype=int)
a3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
a4= np.arange(2,10,2)
a4

array([2, 4, 6, 8])

In [11]:
a5= np.linspace(0,100,5)
a5

array([  0.,  25.,  50.,  75., 100.])

In [12]:
a6= np.identity(5)
a6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

 ### Generate Default randam number

In [13]:
from numpy.random import default_rng
rng = default_rng(12345)
randaom_array= rng.random(5)
randaom_array


array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955])

In [14]:
rng.integers(0,10,100)

array([8, 3, 5, 5, 2, 1, 2, 6, 6, 9, 7, 2, 9, 9, 7, 6, 1, 0, 2, 4, 0, 8,
       4, 6, 2, 3, 1, 7, 7, 2, 7, 0, 3, 1, 7, 3, 4, 4, 4, 2, 5, 8, 4, 1,
       0, 1, 0, 0, 1, 5, 8, 8, 6, 6, 3, 9, 6, 7, 7, 8, 7, 9, 5, 5, 2, 9,
       5, 4, 3, 2, 6, 4, 5, 6, 8, 3, 6, 9, 4, 2, 2, 3, 6, 2, 8, 3, 0, 0,
       0, 6, 3, 2, 6, 0, 5, 6, 0, 1, 3, 3])

In [15]:

rng = default_rng(12345)
mean,stddev = 5 ,1
randaom_normal= rng.normal(mean,stddev, size=10)
randaom_normal


array([3.57617496, 6.26372846, 4.12933826, 4.74082677, 4.92465669,
       4.25911535, 3.6322073 , 5.6488928 , 5.36105811, 3.04713694])

# Assignment 2: Array Creation

Thanks for your help with the first piece - I'm starting to understand some of the key differences between base Python data types and NumPy arrays. 

Does NumPy have anything like the range() function from base Python?

If so: 
* create the same array from assignment 1 using a NumPy function. 
* Make it 5 rows and 2 columns. 
* It's ok if the datatype is float or int.

In [16]:
rng = np.random.default_rng()

random_integers_2d = rng.integers(low=0, high=10, size=(5, 2))
print(f"2D Random Integer Array (0-9):\n{random_integers_2d}\n")

2D Random Integer Array (0-9):
[[2 7]
 [5 9]
 [8 2]
 [2 0]
 [1 8]]



Looking good so far! One of our data scientists asked about random number generation in NumPy.

Can you create a 3x3 array of random numbers between 0 and 1? Use a random state of 2022.

Store the random array in a variable called `random_array`.

In [17]:
rng = np.random.RandomState(2022)

# Create a 3x3 array of random numbers between 0 and 1
random_array = rng.rand(3, 3)

# Print the resulting array
print(random_array)


[[0.00935861 0.49905781 0.11338369]
 [0.04997402 0.68540759 0.48698807]
 [0.89765723 0.64745207 0.89696312]]


### Accessing Array Data

In [18]:
import numpy as np
int_array = np.arange(12)
print(int_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [19]:
print(int_array[:5])

[0 1 2 3 4]


In [20]:
new_array= int_array.reshape(3,4)

In [21]:
print(new_array[::])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
print(new_array[1::])

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
print(new_array[::3])

[[0 1 2 3]]


# Assignment 3: Accessing Array Data


Slice and index the `random_array` we created in the previous exercise. Perform the following:

* Grab the first two 'rows' of the array
* Grab the entire first column
* Finally, grab the second selement of the third row.

Thanks!


In [24]:
print(new_array[::])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
# Grab the first two 'rows' of the array
print(new_array[:2:1])

[[0 1 2 3]
 [4 5 6 7]]


In [26]:
# Grab the entire first column
print(new_array[: , :1])

[[0]
 [4]
 [8]]


In [27]:
# Finally, grab the second selement of the third row.
print(new_array[2][1])

9


In [28]:
ages = np.array([5, 10, 15, 19, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80])
youth_ages = ages[1:4:]
adult_ages = ages[4:14:]
senior_ages = ages[14::]
print(youth_ages)
print(adult_ages)
print(senior_ages)

[10 15 19]
[20 25 30 35 40 45 50 55 60 65]
[70 75 80]


### Arithmetic Operations

In [29]:
import numpy as np 
rng = np.random.default_rng(616)
inventory = rng.integers(0,100,10)
inventory

array([39, 39, 93, 86, 48, 46, 48, 30, 11, 57])

In [30]:
inventory -24

array([ 15,  15,  69,  62,  24,  22,  24,   6, -13,  33])

In [31]:
inventory /2 

array([19.5, 19.5, 46.5, 43. , 24. , 23. , 24. , 15. ,  5.5, 28.5])

In [32]:
price = (rng.random(10) * 10).round(2)
price

array([0.89, 8.82, 7.32, 7.32, 5.62, 3.4 , 0.63, 3.57, 2.03, 4.31])

In [33]:
price * inventory

array([ 34.71, 343.98, 680.76, 629.52, 269.76, 156.4 ,  30.24, 107.1 ,
        22.33, 245.67])

In [34]:
(price * inventory).sum()

np.float64(2520.4700000000003)

In [35]:
# In this exercise, you are provided with arrays representing the ages of residents from two different towns. Your task is to calculate and output the age difference for each corresponding pair of residents from Town A and Town B.
# Population age data for two small towns
town_a_ages = np.array([25, 45, 70, 34, 58])
town_b_ages = np.array([30, 55, 65, 40, 60])

age_differences =town_a_ages -  town_b_ages

age_differences

array([ -5, -10,   5,  -6,  -2])

# Assignment 4: Arithmetic Operations

The creativity of our marketing team knows no bounds!

They've asked us to come up with a simple algorithm to provide a random discount to our list of prices below. 

Before we do that, 

* Add a 5 dollar shipping fee to each price. Call this array `total`.

Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from `random_array`, reshape it to one dimension. Call this `discount_pct`.
* Subtract `discount_pct` FROM 1, store this in `pct_owed`.
* Multiply `pct_owed` by `total` to get the final amount owed.

In [36]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

### Filtering

In [42]:
prices > 12


array([False, False,  True,  True, False,  True])

In [43]:
my_array = np.arange(20)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
my_array  & 2 == 0

array([ True,  True, False, False,  True,  True, False, False,  True,
        True, False, False,  True,  True, False, False,  True,  True,
       False, False])

In [45]:
my_array [my_array % 2 ==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

 ### where 

In [46]:
np.where(my_array % 2 == 0, 'even', 'odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [47]:
np.where(my_array % 2 == 0, 'even', np.where(my_array == 9,my_array, 'odd' )) # nested where

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       '9', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U21')

In [48]:
# This exercise demonstrates how to use the np.where() function to filter data based on a condition. In this case, we identify the indices of all individuals who are considered adults (18 years or older). The function np.where(ages >= 18) evaluates which elements in the ages array meet the condition (ages >= 18). The function returns a tuple of arrays, and the first array contains the indices of these elements. This allows us to easily locate which entries in the original array meet our condition, which is a common task in data analysis when segmenting or filtering data based on criteria.

ages = np.array([25, 12, 15, 64, 35, 80, 45, 10, 22, 55])

adult_ages = np.where(ages >= 18)
 
# Output the indices
print("Ages of adults:", adult_ages)

Ages of adults: (array([0, 3, 4, 5, 6, 8, 9]),)


### Aggregating and Sorting Arrays


In [49]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
print (prices.sum())  #  or print (np.sum(prices))


190.44


In [50]:
print (prices.max())

99.99


In [51]:
print (prices.mean())

31.74


In [52]:
print (np.sum(prices))


190.44


In [53]:
 # SORT

In [54]:
np.sort(price)

array([0.63, 0.89, 2.03, 3.4 , 3.57, 4.31, 5.62, 7.32, 7.32, 8.82])

In [55]:
prices.sort()
price

array([0.89, 8.82, 7.32, 7.32, 5.62, 3.4 , 0.63, 3.57, 2.03, 4.31])

In [56]:
prices.sort(axis=0) # Sort by coloum  and (axis=1) sort by Raws (defults)
price

array([0.89, 8.82, 7.32, 7.32, 5.62, 3.4 , 0.63, 3.57, 2.03, 4.31])

# Assignment 6: Aggregating and Sorting Arrays

This exercise helps you learn how to sort arrays directly in memory with the .sort() method, altering the original data structure, and then directly access the sorted data. After using .sort(), the ages are arranged from the youngest to the oldest, allowing easy retrieval of the minimum and maximum ages. This method is useful for operations requiring rearranged data without preserving the original order, making data analysis workflows both efficient and straightforward.

In [57]:
ages = np.array([25, 12, 15, 64, 35, 80, 45, 10, 22, 55])


# Sort the array in-place
new_array = np.sort(ages)

# Output the sorted array
print (new_array)


# Retrieve and output the minimum and maximum age

min_age = new_array.min()
max_age = new_array.max()
print (min_age)
print (max_age)

[10 12 15 22 25 35 45 55 64 80]
10
80


In [58]:
price_tiers = np.array(["budget", "budget", "mid-tier", "luxury", "mid-tier", "luxury"])

# Assignment 7: Bringing it All Together

Ok, final NumPy task - let's read in some data with the help of Pandas.

Our data scientist provided the code to read in a csv as a Pandas dataframe, and has converted the two columns of interest to arrays.

* Filter `sales_array` down to only sales where the product family was produce. 

* Then, randomly sample roughly half (random number < .5) of the produce sales and report the mean and median sales. Use a random seed of 2022.

* Finally, create a new array that has the values 'above_both', 'above_median', and 'below_both' based on whether the sales were above the median and mean of the sample, just above the median of the sample, or below both the median and mean of the sample. 

In [59]:
import pandas as pd
import numpy as np

retail_df = pd.read_csv(
    "../retail/retail_2016_2017.csv", skiprows=range(1, 11000), nrows=1000
)

family_array = np.array(retail_df["family"])
sales_array = np.array(retail_df["sales"])
#print(sales_array.mean())

In [60]:
produce_array = sales_array [family_array == "PRODUCE"]

rng = np.random.default_rng(2022)
randaom_array = rng.random(30)
sampled_array = produce_array [randaom_array < .5]

In [61]:
mean = sampled_array.mean()
print (mean)

2268.102470588235


In [62]:
median = np.median(sampled_array)
print (median)

1272.755


In [63]:
np.where(

    sampled_array < median,
    "below_both",
    np.where(
        sampled_array > mean, "above_both", "above_median"
    )
)

array(['above_median', 'below_both', 'below_both', 'below_both',
       'above_both', 'below_both', 'below_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'above_both',
       'below_both', 'above_median', 'above_both', 'below_both',
       'above_both'], dtype='<U12')