In [6]:
import sys
print(sys.version)

3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]


In [2]:
# import libraries needed
import numpy as np
import pandas as pd

print(pd.__version__)

3.0.1


In [13]:
 # Hello Pandas

df = pd.DataFrame({
    "name": ["A", "B", "C"],
    "age": [20, 30, 40]
})

print(df)
print('---')
array = np.arange(5)
pd.Series(array)


  name  age
0    A   20
1    B   30
2    C   40
---


0    0
1    1
2    2
3    3
4    4
dtype: int64

In [19]:
series = pd.Series(np.arange(5),name ="test Array")

In [20]:

# pd.Series(np.arange(6).reshape(3,2),name ="test Array") 
#ValueError: Data must be 1-dimensional, got ndarray of shape (3, 2) instead

In [22]:
series.values

array([0, 1, 2, 3, 4])

In [24]:
series.values.mean()

np.float64(2.0)

In [25]:
series.values.sum()

np.int64(10)

In [26]:
series.index

RangeIndex(start=0, stop=5, step=1)

In [27]:
series.name = 'Test ArrayV2'

In [28]:
series.dtype

dtype('int64')

In [31]:
series.astype("float")

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
Name: Test ArrayV2, dtype: float64

In [32]:
series.astype("int")

0    0
1    1
2    2
3    3
4    4
Name: Test ArrayV2, dtype: int64

# Assignment 1: Series Basics

The code has been previded to create an array, `oil_array` from a dataframe column. 

* Convert `oil_array` into a Pandas Series, called `oil_series`. Give it a name!
* Return the name, dtype, size, and index of `oil_series`.

Take the mean of the values array. 

Then, convert the series to integer datatype and recalculate the mean. 


In [160]:
# create a DataFrame from the oil file, drop missing values
oil = pd.read_csv("../retail/oil.csv").dropna()

# Grab 100 rows of oil prices
oil_array = np.array(oil["dcoilwtico"].iloc[1000:1100])
oil_series = pd.Series(oil_array, name= "test")
print(oil_series.name)
print(oil_series.dtype)
print(oil_series.index)
print(oil_series.values.mean())
oil_series = oil_series.astype("int64")
print(oil_series.values.mean())
print(oil_series.dtype)
oil_series = oil_series.astype("float")


test
float64
RangeIndex(start=0, stop=100, step=1)
51.128299999999996
50.66
int64


### Accessing Series Data

In [48]:
series


0    0
1    1
2    2
3    3
4    4
Name: Test ArrayV2, dtype: int64

In [50]:
series[2:4]

2    2
3    3
Name: Test ArrayV2, dtype: int64

In [51]:
series[2]

np.int64(2)

In [76]:
sales = [0,5,155,0,518]
items = ["Coffee","bananas","tea","coconut","sugar"]
sales_series = pd.Series(sales, index=items, name="Sales")


In [77]:
sales_series

Coffee       0
bananas      5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [78]:
sales_series["tea"]

np.int64(155)

In [79]:
sales_series["bananas":"coconut"]

bananas      5
tea        155
coconut      0
Name: Sales, dtype: int64

<b> iloc </b>

In [80]:
print(sales_series.iloc[2])


155


In [81]:
print(sales_series.iloc[[1,3]])

bananas    5
coconut    0
Name: Sales, dtype: int64


<b> loc </b>

In [90]:
print( sales_series.loc["bananas":"coconut"]) 


bananas      5
tea        155
coconut      0
Name: Sales, dtype: int64


In [91]:
sales_series
print( sales_series.loc["tea"]) 


155


<b> Duplicate index values </b>

In [93]:
sales = [0,5,155,0,518]
items = ["Coffee","Coffee","tea","coconut","sugar"]
sales_series = pd.Series(sales, index=items, name="Sales")
sales_series.loc["Coffee"]

Coffee    0
Coffee    5
Name: Sales, dtype: int64

In [95]:
# Reset index
sales_series.reset_index(drop=True)

0      0
1      5
2    155
3      0
4    518
Name: Sales, dtype: int64

# Assignment 2:  Accessing Series Data

* Set the date series, which has been created below, to be the index of the oil price series created in assignment 1.


* Then, take the mean of the first 10 and last 10 prices of the series.


* Finally, grab all oil prices from January 1st, 2017 - January 7th, 2017 (inclusive) and set the index to the default integer index.

In [98]:
# extract date column from oil DataFrame and grab first 100 rows

dates = pd.Series(oil["date"]).iloc[1000:1100]
oil_series.index = dates
oil_series

date
2016-12-20    52
2016-12-21    51
2016-12-22    51
2016-12-23    52
2016-12-27    52
              ..
2017-05-09    45
2017-05-10    47
2017-05-11    47
2017-05-12    47
2017-05-15    48
Name: test, Length: 100, dtype: int64

In [99]:
oil_series.iloc[:10].mean()

np.float64(52.3)

In [100]:
oil_series.iloc[-10:].mean()

np.float64(46.5)

In [105]:
oil_series.loc['2017-01-01':'2017-01-07'].reset_index(drop=True)

0    52
1    53
2    53
3    53
Name: test, dtype: int64


### Filtering Series

In [106]:
sales_series

Coffee       0
Coffee       5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [107]:
sales_series.loc[sales_series > 5] 

tea      155
sugar    518
Name: Sales, dtype: int64

In [108]:
sales = [0,5,155,0,518]
items = ["Coffee","Coffee","tea","coconut","sugar"]
sales_series = pd.Series(sales, index=items, name="Sales")

In [109]:
sales_series

Coffee       0
Coffee       5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [118]:
sales_series.loc[( sales_series >= 5 ) & (sales_series.index == "Coffee")] # And 

Coffee    5
Name: Sales, dtype: int64

In [120]:
# Both gives same output 
sales_series.eq(5) # Pandas method
sales_series == 0 # Python method

Coffee      True
Coffee     False
tea        False
coconut     True
sugar      False
Name: Sales, dtype: bool

In [123]:
sales_series.index.isin(["Coffee","tea"]) # Pandas method IN

array([ True,  True,  True, False, False])

In [125]:
~sales_series.index.isin(["Coffee","tea"]) # Pandas method NOT IN 

array([False, False, False,  True,  True])

In [130]:
sales_series.loc[sales_series.isin([1,2])] # Pandas method IN

Series([], Name: Sales, dtype: int64)

### Sorting

In [131]:
sales_series.sort_index()

Coffee       0
Coffee       5
coconut      0
sugar      518
tea        155
Name: Sales, dtype: int64

In [132]:
sales_series.sort_values()

Coffee       0
coconut      0
Coffee       5
tea        155
sugar      518
Name: Sales, dtype: int64

In [133]:
sales_series.sort_values(ascending=False) # ascending false

sugar      518
tea        155
Coffee       5
Coffee       0
coconut      0
Name: Sales, dtype: int64

# Assignment 3: Sorting and Filtering Series

* First, get the 10 lowest prices from the data. 
* Sort the 10 lowest prices by date, starting with the most recent and ending with the oldest price.

* Finally, use the list of provided dates. Select only rows with these dates that had a price of less than 50 dollars per barrel.

In [158]:
oil = pd.read_csv("../retail/oil.csv").dropna()
# Grab 100 rows of oil prices
oil_array = np.array(oil["dcoilwtico"].iloc[1000:1100])
oil_series = pd.Series(oil_array, name= "test")
oil_series

0     52.22
1     51.44
2     51.98
3     52.01
4     52.82
      ...  
95    45.84
96    47.28
97    47.81
98    47.83
99    48.86
Name: test, Length: 100, dtype: float64

In [152]:
# list of dates to be used to solve bullet 3

dates = [
    "2016-12-22",
    "2017-05-03",
    "2017-01-06",
    "2017-03-05",
    "2017-02-12",
    "2017-03-21",
    "2017-04-14",
    "2017-04-15",
]

In [153]:
oil_series.sort_values().iloc[:10].sort_index(ascending=False)

96    47.28
95    45.84
94    46.46
93    46.23
92    45.55
65    47.02
63    47.00
62    47.29
61    47.02
56    47.24
Name: test, dtype: float64

In [163]:
mask = (oil_series.isin(dates)) & (oil_series <= 50)
oil_series.loc[mask] # Should return values if no check input data file

Series([], Name: test, dtype: float64)

### Series Operations

In [4]:
sales = [0,5,155,0,518]
items = ["Coffee","Coffee","tea","coconut","sugar"]
sales_series = pd.Series(sales, index=items, name="Sales")
sales_series

Coffee       0
Coffee       5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [10]:
## Addition 
sales_series +2 # OR //core python way
sales_series.add(2, fill_value=0) # Pandas Way


Coffee       2
Coffee       7
tea        157
coconut      2
sugar      520
Name: Sales, dtype: int64

In [14]:
## Addition 
sales_series - 2 # OR //core python way
sales_series.sub(2, fill_value=0) # Pandas Way

Coffee      -2
Coffee       3
tea        153
coconut     -2
sugar      516
Name: Sales, dtype: int64

In [16]:
sales_series +sales_series # add two  series

Coffee        0
Coffee       10
tea         310
coconut       0
sugar      1036
Name: Sales, dtype: int64

### Pandas String methods


In [20]:
string_series = pd.Series(["day 0","day 1","day 2","day 3","day 4","day 5"])
string_series

0    day 0
1    day 1
2    day 2
3    day 3
4    day 4
5    day 5
dtype: str

In [25]:
string_series.str.upper().str.contains("1")

0    False
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [35]:
#This line of code targets the second column by its index 1 and changes the data type from string to integer, which is necessary because Pandas reads all split parts as strings by default. Now, you can work with these ages numerically, allowing for operations like sorting, averaging, or summing.
# Provided series with combined age and label data
age_data = pd.Series(['Adult 25', 'Child 12', 'Adult 64', 'Teen 17', 'Adult 45'])

# Split the string to separate the age from the labels
split_data =age_data.str.split(" ",expand=True)
split_data[1] = split_data[1].astype(int)
split_data[1]
# Output the result
print("Split data with Age as an integer:")
print(split_data)

Split data with Age as an integer:
       0   1
0  Adult  25
1  Child  12
2  Adult  64
3   Teen  17
4  Adult  45


### Series Aggregations¶

In [46]:
sales = [0,5,155,0,518]
items = ["Coffee","Coffee","tea","coconut","sugar"]
sales_series = pd.Series(sales, index=items, name="Sales")
print (sales_series.sum())
print (sales_series.loc["Coffee"].sum())
print (sales_series.max())
print (sales_series.max())
print (sales_series.count())


678
5
518
518
5


In [47]:
sales_series.unique()

array([  0,   5, 155, 518])

In [53]:
sales_series.value_counts(normalize=True)

Sales
0      0.4
5      0.2
155    0.2
518    0.2
Name: proportion, dtype: float64

In [ ]:
sales_series.counts(nor)

### Missing Data

In [69]:
sales = [0,5,155,pd.NA, 518]
sales_series = pd.Series(sales, name="Sales",dtype="Int16")
sales_series

0       0
1       5
2     155
3    <NA>
4     518
Name: Sales, dtype: Int16

In [68]:
sales_series.isna() # fomd Nan value

0    False
1    False
2    False
3     True
4    False
Name: Sales, dtype: bool

In [60]:
sales_series.isna().sum() # total na value

np.int64(1)

In [63]:
print(sales_series.value_counts())
print(sales_series.value_counts(dropna=False)) # count including NA

Sales
0      1
5      1
155    1
518    1
Name: count, dtype: Int64
Sales
0       1
5       1
155     1
518     1
<NA>    1
Name: count, dtype: Int64


<b> Handling missing data</b>

In [72]:
sales_series.fillna(0)
sales_series.dropna()

0      0
1      5
2    155
4    518
Name: Sales, dtype: Int16

In [83]:
#In this exercise, you dealt with a series of age data that included missing values and an outlier (age 110). You first used .isna.sum() to determine that there were three missing values in your dataset. Calculating the median with the .median() method, you included all values, even the outlier, because the median is robust to extreme values—unlike the mean, which could have been significantly skewed by the age of 110. This makes the median a safer choice for imputation in such scenarios.

#This method of imputation is particularly useful in real-world data settings where data may not be perfectly clean or uniformly distributed. The filled dataset is more complete and can be used for further analysis without the bias that an extreme value or missing data might introduce

age_data = pd.Series([25, np.nan, 30, 45, 110, 37, np.nan, 42, np.nan, 52])
 
# Calculate the number of missing values
missing_count = age_data.isna().sum()
print("Number of missing values:", missing_count)
 
# Calculate the median of the age data including the outlier
median_age = age_data.median()
 
# Fill missing values with the median age
age_data_filled = age_data.fillna(median_age)
 
# Output the result
print("Data after median imputation:")
print(age_data_filled)

Number of missing values: 3
Data after median imputation:
0     25.0
1     42.0
2     30.0
3     45.0
4    110.0
5     37.0
6     42.0
7     42.0
8     42.0
9     52.0
dtype: float64


 Apply and Where



In [84]:
string_series = pd.Series(["day 0","day 1","day 2","day 3","day 4","day 5"])
string_series

0    day 0
1    day 1
2    day 2
3    day 3
4    day 4
5    day 5
dtype: str

In [85]:
string_series.apply(lambda x: x[-1])

0    0
1    1
2    2
3    3
4    4
5    5
dtype: str

In [98]:
string_series = pd.Series(["day 0","day 1","day 2","day 3","day 4","day 5"])
string_series.where(
    string_series.str.contains("2"),"Nope")

0     Nope
1     Nope
2    day 2
3     Nope
4     Nope
5     Nope
dtype: str

In [106]:
## This exercise demonstrates the practical application of conditional logic using Pandas. By employing the  .where() method with a logical inversion, you efficiently classify the ages into 'Adult' and 'Teen'. This method is not only concise but also showcases a powerful 
#feature of Pandas that can simplify complex logical operations in data processing tasks.

ages = pd.Series([16, 21, 15, 25, 14, 19, 22, 17, 13, 20])

# Use the Pandas .where() function to classify ages
# Anyone 18 or older is classified as "Adult", otherwise "Teen"
age_groups = ages.where(
    ages < 18, "Adult").where(ages > 18, "Teen" )


In [105]:
age_groups

0     Teen
1    Adult
2     Teen
3    Adult
4     Teen
5    Adult
6    Adult
7     Teen
8     Teen
9    Adult
dtype: object